### ISSUE TITLE
remove code duplicates

### ISSUE THREAD

**Issue by michbeck100** [thexperiments/pimatic-netatmo#2]
to make the plugin more maintainable you should try to remove the duplicate code in NetatmoBase and NetatmoIndoorModule. These devices could extend from NetatmoOutdoorModule, because all have the attributes temperature and humidity.

**Comment by thexperiments** [comment]
Thanks for the feedback, this is on the agenda, just wanted to get it done and not yet 100% comfortable with js/coffescript

**Comment by thexperiments** [comment]
First refactoring done. Should be enough to make it much more maintainable. One could further refactor the getDeviceData to use some generic parsing but I will not do this at this point in time as I don't have any test feedback yet for other devices than the ones I own.

see #5
